### PR TITLE
AB#9386 Application List Header

### PR DESCRIPTION
**Pull request by aurelio-aot**
This pull request is to freeze the application list header so that the header will remain visible when the user is scrolling.

https://github.com/bcgov/Unity/assets/97022120/155ebba9-6828-4b3a-9d7c-dba8f63f2b0b

### CODE REVIEW

**Comment by AndreGAot** [comment]
With the header locked in place we lose the column alignment for smaller screens, can we fix this?

Before:
image


Now:

image

**Comment by aurelio-aot** [comment]
hi @AndreGAot -- fixed header alignment is fixed now, thanks to @nitheesh-aot 

image

**Comment by aurelio-aot** [comment]
image

**Review by AndreGAot — APPROVED** [review]
Ready for Dev

**Pull request merged**
