### PR TITLE
AB#9152 application assessment summary

### PR DESCRIPTION
**Pull request by aurelio-aot**

### CODE REVIEW

**Comment by aurelio-aot** [comment]
hi @AndreGAot - this is now ready for review. i created a ticket 9833 to re-implement the code for the following fields once ticket 8819 is merged to dev:

- Organization Name
- Organization Number
- Community

thanks.

**Comment by aurelio-aot** [comment]
> hi @AndreGAot - this is now ready for review. i created a ticket 9833 to re-implement the code for the following fields once ticket 8819 is merged to dev:
> 
> * Organization Name
> * Organization Number
> * Community
> 
> thanks.

sorry, the unit test is still missing, will create the unit test now

**Comment by aurelio-aot** [comment]
> > hi @AndreGAot - this is now ready for review. i created a ticket 9833 to re-implement the code for the following fields once ticket 8819 is merged to dev:
> > 
> > * Organization Name
> > * Organization Number
> > * Community
> > 
> > thanks.
> 
> sorry, the unit test is still missing, will create the unit test now

@AndreGAot - pushed the unit test, this is ready now for your review. thanks.

**Review by AndreGAot — APPROVED** [review]
Ready for Dev

**Pull request merged**
