### PR TITLE
Feature/ab#22962 add contact & ab#22959 edit contact

### PR DESCRIPTION
**Pull request by nitheesh-aot**
[AB#22962](https://tfs.econ.gov.bc.ca/ECON/12d03e79-76dc-4213-a504-6fdfa588b4f6/_workitems/edit/22962) - Add New Contact 
[AB#22959](https://tfs.econ.gov.bc.ca/ECON/12d03e79-76dc-4213-a504-6fdfa588b4f6/_workitems/edit/22959) - Edit Contact Information

### CODE REVIEW

**Comment by AndreGAot** [comment]
@nitheesh-aot  - looks mostly good - can we get some unit tests in too please?

**Comment by nitheesh-aot** [comment]
@AndreGAot Sure, I will raise a new PR for unit tests, please feel free to merge this if you need to give this to testers.

**Comment by AndreGAot** [comment]
@nitheesh-aot - will wait for the unit tests, thanks

**Comment by nitheesh-aot** [comment]
added unit tests @AndreGAot

**Comment by nitheesh-aot** [comment]
not sure why, but only 15 commits are showing in this PR now. where the feature branch has 17.

**Comment by AndreGAot** [comment]
@nitheesh-aot - please follow up with BA / Max around the field validations for the email and the mobile numbers (story doesn't specify anything but i think it is presumed) - also the delete contact button doesn't seem to work

**Review by AndreGAot — APPROVED** [review]
Ready for Dev

**Pull request merged**
