### PR TITLE
AB#22937 Editable fields after approval

### PR DESCRIPTION
**Pull request by aurelio-aot**

### CODE REVIEW

**Comment by AndreGAot** [comment]
@aurelio-aot  - would like to chat about this one first -> there are some real business rules being implemented here that need to move down to the domain layer - also would like to revalidate those rules again with business

**Comment by AndreGAot** [comment]
@aurelio-aot  - please review and let me know if all good

**Comment by aurelio-aot** [comment]
code tested and worked. need to run the script first.

**Review by AndreGAot — APPROVED** [review]
Ready for Dev

**Pull request merged**
