### PR TITLE
AB#23432 Correctly display attachment tab status

### PR DESCRIPTION
**Pull request by aurelio-aot**

### CODE REVIEW

**Comment by aurelio-aot** [comment]
hi @AndreGAot -- i've tested and pushed now the code that you shared, its all working well.  Thanks.

**Comment by aurelio-aot** [comment]
@AndreGAot  will work now on refactoring the chefs attachment into a separate widget. thanks

**Comment by aurelio-aot** [comment]
hi @AndreGAot -- this is now ready for another round of review. thanks.

**Review by AndreGAot — APPROVED** [review]
Ready for Dev

**Pull request merged**
